# name|git_url|checkout_path
feaon|https://github.com/khoawatt/Feaon-ldp-v2.git|~/projects/personal/Feaon-ldp-v2
qvak|https://github.com/khoawatt/qvak-portfolio.git|~/projects/personal/qvak-portfolio
